### ISSUE TITLE
Can use this themes in shared hosting ? (cant npm)

### ISSUE THREAD

**Issue by anonprophet** [320press/wordpress-bootstrap#237]
`cd path/to/wp-content/themes
git clone https://github.com/320press/wordpress-bootstrap.git
npm install
grunt dev`

im using shared hosting with cpanel
i cant run command above, can i just download and exctract in wp-content/themes ?

**Comment by eduardoarandah** [comment]
yes

**Comment by anonprophet** [comment]
thanks, for what is ``grunt dev`` ?

sorry for newbie question

**Comment by eduardoarandah** [comment]
If you want to modify the theme, you can do it Via  Less files. 
Less files are css files but with variables. 
If you run grunt dev, grunt watch changes and creates css files. 
Really recommend you to learn less, grunt, npm
